import { EquipmentItem, ServiceItem, ClientReview } from "@/types/rental";

export const SERVICES_LIST: ServiceItem[] = [
  {
    id: "video-production",
    idx: "01",
    title: "Video Production",
    description: "Film & commercial production — TVCs, commercials, brand films and music videos, built end to end.",
    href: "/video-production",
    linkText: "EXPLORE →",
    icon: "video",
    glowColor: "var(--orange)",
  },
  {
    id: "equipment-rental",
    idx: "02",
    title: "Equipment Rental",
    description: "Fujifilm, Sony, RED, Blackmagic, Aputure & DJI — rent individually or bundled, delivered ready to shoot.",
    href: "/equipment-rental",
    linkText: "VIEW EQUIPMENT →",
    icon: "camera",
    glowColor: "#7a3c12",
  },
  {
    id: "studio-rental",
    idx: "03",
    title: "Studio Rental",
    description: "A fully-equipped 360m² studio with cyclorama, grip and full blackout control — book by the hour.",
    href: "/studio-rental",
    linkText: "BOOK THE STUDIO →",
    icon: "building",
    glowColor: "var(--orange)",
  },
  {
    id: "podcast-studio",
    idx: "04",
    title: "Podcast Studio",
    description: "Talking-head & podcast packages — multi-cam, lit set and clean audio, ready to record.",
    href: "/podcast-talking-head-video",
    linkText: "BOOK A SESSION →",
    icon: "mic",
    glowColor: "#5a3a14",
  },
];

export const EQUIPMENT_CATALOGUE: EquipmentItem[] = [
  {
    id: "fuji-xh2s-fullset",
    name: "FUJIFILM X-H2S | FULLSET",
    brand: "Fujifilm",
    category: "camera",
    dailyPrice: 650000,
    formattedPrice: "650.000đ",
    image: "/images/remus-set-2fc87.jpg",
    description: "Fujifilm flagship cinema & video hybrid, 6.2K open gate, ProRes internal recording, high speed 4K 120p.",
    specs: ["26.1MP X-Trans BSI Stacked", "6.2K 30p / 4K 120p ProRes", "7-stop IBIS", "F-Log2 Dynamic Range"],
    featured: true,
  },
  {
    id: "fuji-xt5-body",
    name: "FUJIFILM X-T5 | BODY",
    brand: "Fujifilm",
    category: "camera",
    dailyPrice: 500000,
    formattedPrice: "500.000đ",
    image: "/images/camera-rigaaf7.jpg",
    description: "40.2MP high-resolution photography & 6.2K video body with classic dial controls.",
    specs: ["40.2MP X-Trans 5 HR", "6.2K 30p 4:2:2 10-Bit", "7-stop 5-axis IBIS", "Dual SD Slots"],
    featured: true,
  },
  {
    id: "fuji-gfx100-ii",
    name: "FUJIFILM GFX 100 II | MEDIUM FORMAT",
    brand: "Fujifilm",
    category: "camera",
    dailyPrice: 1800000,
    formattedPrice: "1.800.000đ",
    image: "/images/equip-feature28c4.jpg",
    description: "102MP Medium Format sensor with 8K 30p & 4K 60p ProRes cinema recording capabilities.",
    specs: ["102MP BSI CMOS Medium Format", "8K 30p / 4K 60p ProRes", "8-stop IBIS", "Waveform / Vectorscope"],
    featured: true,
  },
  {
    id: "sony-fx3-fullset",
    name: "SONY FX3 | FULLSET",
    brand: "Sony",
    category: "camera",
    dailyPrice: 1300000,
    formattedPrice: "1.300.000đ",
    image: "/images/rig-pictor601b.jpg",
    description: "Full-frame cinema line body, dual base ISO 800/12800, 4K 120p 10-bit 4:2:2, cage, V-mount, monitor.",
    specs: ["Full-Frame 12.1MP Exmor R", "Dual Base ISO 800/12800", "4K 120p Raw Output", "Cage & V-mount Battery"],
    featured: true,
  },
  {
    id: "sony-fx6-fullset",
    name: "SONY FX6 | FULLSET",
    brand: "Sony",
    category: "camera",
    dailyPrice: 2000000,
    formattedPrice: "2.000.000đ",
    image: "/images/rig-sea0877.jpg",
    description: "Industry-standard cinema line camera with built-in variable ND, SDI output and XLR audio.",
    specs: ["Full-Frame 4K Sensor", "Electronic Variable ND", "16-bit RAW output", "Dual CFexpress Type A"],
    featured: true,
  },
  {
    id: "arri-alexa-mini",
    name: "ARRI ALEXA MINI | FULLSET",
    brand: "ARRI",
    category: "camera",
    dailyPrice: 5500000,
    formattedPrice: "5.500.000đ",
    image: "/images/hero-cinematiccbed.jpg",
    description: "Legendary ARRI color science, ALEV III sensor, PL mount, production rig, ready for feature film.",
    specs: ["ALEV III Sensor", "ARRIRAW & ProRes", "14+ stops Dynamic Range", "Full Cine Accessories"],
    featured: true,
  },
  {
    id: "red-komodo-x",
    name: "RED KOMODO X | FULLSET",
    brand: "RED",
    category: "camera",
    dailyPrice: 2800000,
    formattedPrice: "2.800.000đ",
    image: "/images/equip-hero6c7f.jpg",
    description: "6K S35 Global Shutter, 6K 80fps, 4K 120fps REDCODE RAW, RF mount with locking ring.",
    specs: ["6K Global Shutter Sensor", "REDCODE RAW 6K 80fps", "Integrated V-Mount", "12G-SDI Output"],
    featured: true,
  },
  {
    id: "blackmagic-pyxis-6k",
    name: "BLACKMAGIC PYXIS 6K | FULLSET",
    brand: "Blackmagic",
    category: "camera",
    dailyPrice: 1500000,
    formattedPrice: "1.500.000đ",
    image: "/images/studio-setaaf7.jpg",
    description: "Full-frame 6K cinema camera with box design, EF/PL mount, 13 stops dynamic range, dual CFexpress.",
    specs: ["Full Frame 6048 x 4032", "Open Gate 6:5 Anamorphic", "Blackmagic RAW 12-Bit", "Dual native ISO"],
    featured: true,
  },
  {
    id: "fujinon-xf-16-55",
    name: "FUJINON XF 16-55MM F2.8 R LM WR",
    brand: "Fujifilm",
    category: "lens",
    dailyPrice: 250000,
    formattedPrice: "250.000đ",
    image: "/images/op-sea8211.jpg",
    description: "Standard zoom red-badge lens with constant f/2.8 aperture and weather resistance.",
    specs: ["Focal length: 16-55mm (24-84mm eq)", "Constant f/2.8 aperture", "Linear Motor AF", "Weather sealed"],
  },
  {
    id: "zeiss-cp3-set",
    name: "CARL ZEISS CP.3 PRIME SET (6 LENSES)",
    brand: "Zeiss",
    category: "lens",
    dailyPrice: 2400000,
    formattedPrice: "2.400.000đ",
    image: "/images/work-fired3f4.jpg",
    description: "Compact Prime CP.3 set (15, 25, 35, 50, 85, 100mm) PL mount with standard gear rings.",
    specs: ["Full frame coverage", "Consistent color balance", "Standard 95mm front diameter", "Smooth focus throw"],
  },
  {
    id: "dzo-vespid-prime-set",
    name: "DZOFILM VESPID PRIME PL SET (6 LENSES)",
    brand: "DZOFILM",
    category: "lens",
    dailyPrice: 1600000,
    formattedPrice: "1.600.000đ",
    image: "/images/th-warm2167.jpg",
    description: "Cine prime lens set with T2.1 aperture, pleasing bokeh, organic falloff and compact design.",
    specs: ["16, 25, 35, 50, 75, 100mm T2.1", "PL / EF Interchangeable", "80mm front diameter", "16-blade iris"],
  },
  {
    id: "aputure-1200d",
    name: "APUTURE 1200D PRO COB LIGHT",
    brand: "Aputure",
    category: "lighting",
    dailyPrice: 800000,
    formattedPrice: "800.000đ",
    image: "/images/studio-gradient2167.jpg",
    description: "1200W Daylight point-source LED, Bowens mount, comparable to 1.6kW HMI or 1800W Tungsten.",
    specs: ["1200W Output 5600K", "CRI/TLCI 96+", "IP54 Weather Resistance", "Sidus Link App Control"],
  },
  {
    id: "aputure-600d-pro",
    name: "APUTURE 600D PRO COB LIGHT",
    brand: "Aputure",
    category: "lighting",
    dailyPrice: 550000,
    formattedPrice: "550.000đ",
    image: "/images/studio-setaaf7.jpg",
    description: "600W Daylight LED with high-output hyper reflector, IP54 weather-proof, built-in FX.",
    specs: ["600W Daylight 5600K", "CRI 96, TLCI 96", "Bowens Mount", "V-mount battery power ready"],
  },
  {
    id: "dji-rs4-pro",
    name: "DJI RS4 PRO GIMBAL COMBO",
    brand: "DJI",
    category: "gimbal",
    dailyPrice: 400000,
    formattedPrice: "400.000đ",
    image: "/images/rig-pictorfafb.jpg",
    description: "4.5kg payload capacity, carbon fiber arms, automated axis locks, LiDAR focusing support.",
    specs: ["4.5kg Tested Payload", "OLED Touchscreen", "LiDAR Range Finder support", "2nd-Gen Automated Locks"],
  },
  {
    id: "dji-mavic-3-pro",
    name: "DJI MAVIC 3 PRO FLY MORE (RC2)",
    brand: "DJI",
    category: "drone",
    dailyPrice: 800000,
    formattedPrice: "800.000đ",
    image: "/images/crew-on-location6c9c.jpg",
    description: "Tri-camera system with 4/3 CMOS Hasselblad camera, 70mm and 166mm telephoto cameras.",
    specs: ["Hasselblad 4/3 CMOS 5.1K", "Triple Camera Setup", "43-Min Max Flight Time", "Omnidirectional Obstacle Sensing"],
  },
];

export const CLIENT_REVIEWS: ClientReview[] = [
  {
    id: "rev-1",
    quote:
      "Within five minutes, I knew he was my guy — his beautiful spirit, communication skills and amazing personality. We ended up working 15-hour days. His editing skills are superb… everyone was patient and always professional. In the future, I am going to fly him and the team to America whenever I have a project.",
    author: "Valentino Dixon",
    role: "Artist & Exoneree",
    location: "Subject of an Emmy-Nominated Story",
    rating: 5,
    initials: "VD",
    gradient: "linear-gradient(135deg,#c79338,#6e4a14)",
  },
  {
    id: "rev-2",
    quote:
      "I'm a psychotherapist from the UK and spent a whole day here. Amazing team, high-quality production, so friendly and kind, and great cameras. The level of English was amazing — better service than western production studios I have been to. Highly recommended, and I will be back.",
    author: "Sophia Spencer",
    role: "Psychotherapist",
    location: "United Kingdom",
    rating: 5,
    initials: "SS",
    gradient: "linear-gradient(135deg,#7a2149,#38101f)",
  },
  {
    id: "rev-3",
    quote:
      "This is truly a wonderful place that meets all of your filming needs. Spacious space, modern equipment, and an experienced, patient team. I'll be back to film again soon.",
    author: "Anthony Dillo",
    role: "Actor",
    location: "United States",
    rating: 5,
    initials: "AD",
    gradient: "linear-gradient(135deg,#9a3324,#41130d)",
  },
  {
    id: "rev-4",
    quote:
      "We rented out a full package setup for the Blackmagic Pyxis 6K, and Vespid lens set… Jack and his crew are young, motivated and very professional — offering up suggestions and solutions as we go along, which made my directorial life way easier.",
    author: "Kevin Lee",
    role: "Film Director",
    location: "Singapore",
    rating: 5,
    initials: "KL",
    gradient: "linear-gradient(135deg, #ff6b1a, #c84f0c)",
    textColor: "#0A0A0B",
  },
  {
    id: "rev-5",
    quote:
      "The equipment is truly top-tier, and the studio itself offers an impressive range of creative possibilities… It felt less like renting a studio and more like collaborating with a passionate creative team. We'll definitely be back.",
    author: "Victor Shohreh",
    role: "Podcast Producer",
    location: "Germany",
    rating: 5,
    initials: "VS",
    gradient: "linear-gradient(135deg,#5a2e8a,#2a1340)",
  },
  {
    id: "rev-6",
    quote:
      "L'expérience à Cinefy est juste incroyable ! Je suis venu tourner une vidéo YouTube et la qualité est professionnelle ! Digne d'un studio de cinéma !",
    author: "Mr Dreamax (Cyril NKM)",
    role: "YouTuber · 2M+ subscribers",
    location: "France",
    rating: 5,
    initials: "MD",
    gradient: "linear-gradient(135deg,#1c3346,#0f1a24)",
  },
  {
    id: "rev-7",
    quote:
      "Our first time using this location — we're UGC and content creators, and since moving to Vietnam we wanted a place with great lighting to take our content and photography to the next level. Cinefy exceeded our expectations.",
    author: "Remington Flores",
    role: "UGC & Content Creator",
    location: "Vietnam",
    rating: 5,
    initials: "RF",
    gradient: "linear-gradient(135deg,#2e6a5a,#123a30)",
  },
];
